/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guihw;
import java.text.DecimalFormat;
/**
 *
 * @author Cloudaerius
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        messageLabel = new javax.swing.JLabel();
        fahrenheitInput = new javax.swing.JTextField();
        convertedOutput = new javax.swing.JLabel();
        convertButton = new javax.swing.JButton();
        fehrenheitRadioBtn = new javax.swing.JRadioButton();
        celciusRadioBtn = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        messageLabel.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        messageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        messageLabel.setText("Enter the degrees you wish to convert and select what measurement you want to convert to");

        fahrenheitInput.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        fahrenheitInput.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        convertedOutput.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        convertedOutput.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        convertedOutput.setText("Converted");

        convertButton.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        convertButton.setText("Convert");
        convertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convertButtonActionPerformed(evt);
            }
        });

        fehrenheitRadioBtn.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        fehrenheitRadioBtn.setSelected(true);
        fehrenheitRadioBtn.setText("Fehrenheit");

        celciusRadioBtn.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        celciusRadioBtn.setText("Celcius");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(fehrenheitRadioBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(celciusRadioBtn))
                    .addComponent(messageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(fahrenheitInput)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(convertedOutput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(106, 106, 106)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(260, Short.MAX_VALUE)
                .addComponent(convertButton, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(260, 260, 260))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(messageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fehrenheitRadioBtn)
                    .addComponent(celciusRadioBtn))
                .addGap(18, 18, 18)
                .addComponent(fahrenheitInput, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(convertedOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(convertButton, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void convertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convertButtonActionPerformed
        // TODO add your handling code here:
        DecimalFormat df = new DecimalFormat("0.00");
        String input = fahrenheitInput.getText();
        String degreeTypeOutput = null;
        ConverterService convertDegrees = new FahrenheitConverter();
        ConvertStringToDoubleStrategy convertedString = new ConvertStringToDoubleStrategy();
        if(fehrenheitRadioBtn.isSelected()){
         convertDegrees = new FahrenheitConverter();
         degreeTypeOutput = "F";
        }
        if(celciusRadioBtn.isSelected()){
            convertDegrees = new CelciusConverter();
            degreeTypeOutput = "C";
        }
        double convertedStringNumber = convertDegrees.getConvertDegrees(convertedString.convertString(input));
        
        String outputNumber = Double.toString(convertedStringNumber);
        
        convertedOutput.setText(outputNumber + "\u00b0 " + degreeTypeOutput);
    }//GEN-LAST:event_convertButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JRadioButton celciusRadioBtn;
    private javax.swing.JButton convertButton;
    private javax.swing.JLabel convertedOutput;
    private javax.swing.JTextField fahrenheitInput;
    private javax.swing.JRadioButton fehrenheitRadioBtn;
    private javax.swing.JLabel messageLabel;
    // End of variables declaration//GEN-END:variables
}
